[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chianlink/contracts/=lib/chianlink-brownie-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
